# Generated by Django 5.2.12 on 2026-03-31 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_is_banned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('event_date', models.DateField(verbose_name='Дата события')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Галерея',
                'ordering': ['-event_date'],
            },
        ),
        migrations.AddField(
            model_name='achievement',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='main.tournament', verbose_name='Турнир'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Завершен'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=1000, verbose_name='Рейтинг Elo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Администратор'), ('trainer', 'Тренер')], default='user', max_length=10),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('issued_at', models.DateField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='main.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClubMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('location', models.CharField(max_length=200, verbose_name='Место проведения')),
                ('max_participants', models.IntegerField(default=30, verbose_name='Максимум участников')),
                ('participants', models.ManyToManyField(blank=True, related_name='meetings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('result', models.CharField(choices=[('white_win', 'Белые выиграли'), ('black_win', 'Чёрные выиграли'), ('draw', 'Ничья')], max_length=10)),
                ('pgn', models.TextField(blank=True, verbose_name='Запись партии (PGN)')),
                ('analysis', models.TextField(blank=True, verbose_name='Анализ партии')),
                ('black_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_black', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='main.tournament')),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_white', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Звание')),
                ('experience', models.IntegerField(default=0, verbose_name='Лет опыта')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Специализация')),
                ('rating', models.FloatField(default=5.0, verbose_name='Рейтинг тренера')),
                ('students_count', models.IntegerField(default=0, verbose_name='Количество учеников')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен для занятий')),
                ('about', models.TextField(blank=True, verbose_name='О себе')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='trainers/')),
                ('achievements', models.TextField(blank=True, verbose_name='Достижения')),
                ('price_per_hour', models.IntegerField(default=1000, verbose_name='Цена за час (руб)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название урока')),
                ('description', models.TextField(verbose_name='Описание')),
                ('type', models.CharField(choices=[('individual', 'Индивидуальное'), ('group', 'Групповое')], default='group', max_length=10)),
                ('mode', models.CharField(choices=[('online', 'Онлайн (Zoom / Яндекс.Телемост)'), ('offline', 'Офлайн (в клубе)')], default='online', max_length=10)),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('duration', models.IntegerField(default=60, verbose_name='Длительность (мин)')),
                ('max_students', models.IntegerField(default=10, verbose_name='Максимум учеников')),
                ('meeting_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на занятие (Zoom/Телемост)')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Адрес (для офлайн)')),
                ('students', models.ManyToManyField(blank=True, related_name='lessons', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='main.trainer')),
            ],
        ),
    ]
