# Generated by Django 5.2.12 on 2026-05-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_game_black_player_remove_game_tournament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='mode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
